from __future__ import annotations

from pathlib import Path

from hcb_tool.core.binary_io import read_bytes
from hcb_tool.formats.registry import find_best_plugin, iter_plugins
from hcb_tool.services.io_utils import read_json

PROJECT_IR_NAME = "project_ir.json"


def resolve_project_ir_path(source: str | Path) -> Path | None:
    """Return the machine-readable IR generated by the disassembly step.

    The intended v0.3 workflow is disassembly-first:
      original.hcb -> disasm.txt + project_ir.json -> text/chapter export/import

    A directory source may be either the per-file disassembly directory
    (containing project_ir.json) or the outer disasm folder containing exactly one
    per-file directory.
    """
    p = Path(source)
    if p.is_file() and p.name == PROJECT_IR_NAME:
        return p
    if p.is_dir():
        direct = p / PROJECT_IR_NAME
        if direct.is_file():
            return direct
        found = sorted(p.glob(f"*/{PROJECT_IR_NAME}"))
        if len(found) == 1:
            return found[0]
    return None


def load_ir_from_source(source: str | Path, options: dict | None = None, include_disasm: bool = False) -> tuple[dict, object]:
    """Load an IR from the disassembly project, project_ir.json, ir.json, or HCB.

    v0.3 GUI uses only project_ir.json generated by the 反汇编/建立工程 step.
    Direct .hcb loading remains for CLI/backward compatibility and one-off
    debugging, but it is no longer the GUI extraction principle.
    """
    options = options or {}
    p = Path(source)

    project_ir = resolve_project_ir_path(p)
    if project_ir is not None:
        p = project_ir

    if p.name.lower() in {PROJECT_IR_NAME, "ir.json"} or p.suffix.lower() == ".json":
        ir = read_json(p)
        plugin_id = ir.get("manifest", {}).get("plugin_id")
        plugin = next((plg for plg in iter_plugins() if plg.plugin_id == plugin_id), None)
        if plugin is None:
            raise ValueError(f"no plugin for IR plugin_id={plugin_id}")
        return ir, plugin

    if options.get("require_project_ir"):
        raise FileNotFoundError(
            f"找不到反汇编工程 IR：{PROJECT_IR_NAME}。请先执行 反汇编/建立工程，"
            "再从反汇编结果提取文本/章节。"
        )

    # Backward-compatible CLI/debug path.  GUI should not use this.
    data = read_bytes(p)
    plugin, score = find_best_plugin(p, data)
    decoded, layer_info = plugin.decode_layers(data, options)
    ir = plugin.disassemble(p, decoded, {**options, "mode": options.get("mode", "lean"), "include_disasm": include_disasm})
    ir["probe_score"] = score
    ir["layer_info"] = layer_info
    ir.setdefault("manifest", {})["derived_from"] = "direct_hcb_debug_path"
    return ir, plugin
